### ISSUE TITLE
ImportError: No module named ntpath on Anki

### ISSUE THREAD

**Issue by AndreiBarsan** [Stvad/CrowdAnki#10]
I have Anki 2.0.36, Qt 4.8.2 PyQt 4.9.4, on OS X 10.11.6.

I've installed the AnkiHub add-on, and then CrowdAnki. I've removed all other add-ons and I'm sadly still getting the error.

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/andrei/Documents/Anki/addons/crowd_anki_importer.py", line 1, in <module>
  File "/Users/andrei/Documents/Anki/addons/crowd_anki/main.py", line 1, in <module>
  File "/Users/andrei/Documents/Anki/addons/crowd_anki/thirdparty/pathlib.py", line 1, in <module>
  File "/Users/andrei/Documents/Anki/addons/crowd_anki/thirdparty/pathlib2.py", line 5, in <module>
ImportError: No module named ntpath
```

This doesn't crash Anki, but only makes the CrowdAnki plugin unusable. Please do let me know if you need additional details.

**Comment by Stvad** [comment]
Thank you for reporting this.
I strongly suspect that it's because Anki don't have complete python env installed alongside with it and it's incomplete in different ways on different platforms. I was not able to test it on OSX machine so far, as I don't have any. But I will figure something out.

**Comment by Stvad** [comment]
@AndreiBarsan I'm setting up os-x vm now. But it may prove faster if you could try this version: 
[crowd_anki_0.4.2.zip](https://github.com/Stvad/CrowdAnki/files/488134/crowd_anki_0.4.2.zip)

**Comment by Stvad** [comment]
Ok, so I got my VM running. There is more dependencies.

**Comment by Stvad** [comment]
I've uploaded new release that should fix dependencies problems. Please give it a try and let me know how it works for you!
