### ISSUE TITLE
Some insight about Anki.

### ISSUE THREAD

**Issue by gavenkoa** [Stvad/CrowdAnki#11]
I didn't find your mail address so use ticket for this purpose.

Recently I decided to pull my personal dictionary to some SRS with requirement that subsequent updates can be merged with preserving learning progress. Among free SRS with mobile clients only Anki with AnkiDroid able to do that.

You may interested in my adventure:

* https://anki.tenderapp.com/discussions/ankidesktop/19429-any-way-to-build-apkg-from-command-line-without-gui
* https://anki.tenderapp.com/discussions/ankidesktop/19461-is-it-possible-to-merge-improvements-and-corrections-to-cards-during-apkg-import-without-loosing-progress

My solution for preserving `node.guid` is based on hashing headword with mixing of file name and card type. Also `model['id']` should be preserved and it is generated from file name. Details at http://hg.defun.work/gadict/file/tip/py/gadict_srs_anki.py

I think that JSON is not appropriate for unqualified users. You should consider FAQ format because of it verbosity. You may get idea from AnyMemo specification:

https://web.archive.org/web/20160309022328/http://anymemo.org/index.php?page=amc-guide1

I think line oriented format works the best, as illustration:

    model-id: 123456789123456789 (8 byte integer is about 18 digit number)
    model-css: ...

    guid: xxx-xxx-yyy  (sqlite type text - any string sequence)
    Q: Hello from Dnipro!
    A: Привіт з Дніпра!
    PRON: prɪvit z dniprɑ

May be YAML another good option instead of JSON. It verbose for ordinary users and keeps structure for programming access.

**Comment by dayjaby** [comment]
The exported JSON is not meant to be edited manually by "unqualified" users. So I don't understand why verbosity should be a necessary feature.

One great feature of this pretty-printed JSON is that git recognizes changes to single fields in Anki, and commiting those changes to git results in really small changes, because only one single line is changed.

If you want to see an example of what I mean: In [this commit](https://github.com/dayjaby/Kumo/commit/6adcd47ce50ba8c986af0ca1686aea17b6ebcb5f), I added a new note in Anki (the big green block at the top) and changed a few other single fields, which are those one-line updates at the bottom.

Of course your suggested FAQ format would result only in one-line updates as well, but such a hand-crafted format is always inferior to robust formats like JSON.

**Comment by gavenkoa** [comment]
I forgot that JSON can be formatted in a similar way as other line-oriented formats. In that case it is possible to collaborate via DVCS.

**Comment by gavenkoa** [comment]
**FAQ format** may not be restricted to single line.

Common approach is **folding** like a usage of leading space in https://tools.ietf.org/html/rfc2822#section-2.2.3

Another example is indentation used by YAML.

In any way you are not interested in human editable source format but in intermediate format and JSON can served this purpose well.

**Comment by Stvad** [comment]
Hey @gavenkoa. Thank you for your feedback! :smiley: 
You can find my email at my github profile page :).

As @dayjaby mentioned the main purpose here was not to provide a human readable format for users to create cards (though I kept that at the back of my mind and done some work towards enabling this type of cards creation), but the format that will allow people to effectively collaborate via tools like github. While doing most of the card editing inside of the Anki (and having all reach tools to do that at their disposal).

I also do handle updates of the notes with the same uuid without losing progress. You can look at the code to get more details on this one. 
Thank you again for sharing your thoughts and perspective.

I'm looking forward to your feedback on using the plugin!

**Comment by sudomain** [comment]
> One great feature of this pretty-printed JSON is that git recognizes changes to single fields in Anki, and commiting those changes to git results in really small changes, because only one single line is changed.

I realize I'm commenting on an closed issue 4 years later, but for informational purposes I'd like to point out that [git commits are like a series of snapshots, rather than delta-based like other VCS](https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F)
