### ISSUE TITLE
Exporter retains deck config uuid despite not including config profile in exported JSON

### ISSUE THREAD

**Issue by newageoflight** [Stvad/CrowdAnki#116]
Issue: as title.

To reproduce:
1. Have another person import an Anki deck not having your config profiles and then export it back to you.
2. Perform some edits and have them reimport your export.
3. The importer will throw an error saying it detected a nonexistent "deck_config_uuid"

Platform: Anki 2.1.35, Windows

![137213513_704182567133602_8824641045323812466_n](https://user-images.githubusercontent.com/33755603/104302520-00288480-551d-11eb-8290-6db6882bcc68.png)

**Comment by aplaice** [comment]
Thanks for reporting and I'm sorry that you're bitten by the bug!

I _think_ that this is closely related to #106. (I'm linking it purely for informational/reference purposes — it doesn't have any sort of general workaround or solution (other than editing the JSON which is obviously horribly inconvenient).)

I'll try to fix this (along the lines of **3** [here](https://github.com/Stvad/CrowdAnki/issues/106#issuecomment-723312413)), if I have time, this week, but if anybody else wants to have a go, then please feel free! :)

(Ideally, in addition to fixing *export*, we'd also provide some sort of special-case treatment for importing the broken JSONs that `CrowdAnki` had exported.)
