### ISSUE TITLE
Wrong Note Type is Exported

### ISSUE THREAD

**Issue by ohare93** [Stvad/CrowdAnki#123]
I have just exported a rather large deck that I use as a collection for a bunch of random cards which I have too few off to generate a deck of their own (aptly named: "Miscellaneous"). At some point in the distant past I duplicated a Note Type "Basic-Knowledge-With-Context" (let's call it NoteTypeA) to create pretty much the same note type called "BSL" (let's call it NoteTypeB), but minus the two last fields. I used the Anki Note Model Manager window to do this.

The issue: On export of this big joint deck Notes of type NoteTypeB are considered to be of NoteTypeA (their note_model_uuid is set to it) and NoteTypeB is not even exported (though NoteTypeA is). I imagine the CrowdAnki_UUID is identical for the second note type, though I have no idea where I may find that in my local files or how I may correct this error.

Happy to look into it myself if I have time, but if someone else knows an easy fix it would be mighty appreciated :+1: For now I am simply removing these cards from my export.

**Comment by aplaice** [comment]
I suspect this is identical to #121. Hopefully the "General diagnosis" and "General (non-permanent) fix" should work for you!
