### ISSUE TITLE
aeraer

### ISSUE THREAD

**Issue by marksteadman080592** [Stvad/CrowdAnki#125]
i dont understand how your thing works and it doesn't work on my anki how the fuck do you use git
fvdregegerg
re
e
re
re
rer
e
re
er
e
e
e
e
e

e
e
e

e
e
e

e
e

e
er
e
r
er

er
e
r
aer
aer

area
er

**Comment by marksteadman080592** [comment]
this is infruriating

**Comment by ohare93** [comment]
:sweat_smile: 

Have you tried to install the add-on? Do so from here https://ankiweb.net/shared/info/1788670778 Scroll down to the downloads section and copy the number shown. 

> If you were linked to this page from the internet, please open Anki on your computer, go to the Tools menu and then Add-ons>Browse & Install to paste in the code.

If something fails, let us know exactly what. A screenshot may help. Which version of Anko are you using?

**Comment by Stvad** [comment]
Seems like spam to me closing for now. Please open issue with more details in case this is a mistake
