### ISSUE TITLE
does anyone on this website speak english and not solely talk in acronyms

### ISSUE THREAD

**Issue by marksteadman080592** [Stvad/CrowdAnki#126]
i dont understand how your thing works and it doesn't work on my anki how the fuck do you use git
fvdregegerg
re
e
re
re
rer
e
re
er
e
e
e
e
e

e
e
e

e
e
e

e
e

e
er
e
r
er

er
e
r
aer
aer

area
er

**Comment by marksteadman080592** [comment]
why do people on the internet speak in morse fucking code?

**Comment by ohare93** [comment]
Lol, I presume the double post was accidental :sweat_smile: 

> why do people on the internet speak in morse fucking code?

What do you mean, exactly?

Help us help you, mate :+1:

**Comment by Stvad** [comment]
Seems like spam to me closing for now. Please open a new issue with more details or reply here in case this is a mistake
