### ISSUE TITLE
Different alphabets error

### ISSUE THREAD

**Issue by andresos** [Stvad/CrowdAnki#14]
When importing a Japanese deck, the plugin gives the error "charmap"

**Comment by Stvad** [comment]
Hi, thank you for reporting this. Can you please give me more information to work with?
E.g. your operating system, the full text of an error and example of the card (json file, you're trying to import).

**Comment by andresos** [comment]
Of course. I'm using Windows, the full text of the error is only the one I wrote before (charmap)
![image](https://cloud.githubusercontent.com/assets/18708235/19906963/8f3f422e-a042-11e6-9061-8105ac3bf4c3.png)

Also, I the repository for the deck I'm trying to import is on andresos/MNN1, but if you prefer, I have attached the deck in .apkg format

Thanks!

[MNN1.zip](https://github.com/Stvad/CrowdAnki/files/565038/MNN1.zip)

**Comment by Stvad** [comment]
I see, thank you, I will look into it in the next few days.

**Comment by Stvad** [comment]
I've created a new release, that should fix the problem. Update is available via AnkiHub and AnkiWeb.
