### ISSUE TITLE
Lots of deprecated items when starting anki with crowdanki

### ISSUE THREAD

**Issue by boydkelly** [Stvad/CrowdAnki#142]
This is using latest anki.   2.1.48   (There are a *lot* of joinedFields messages)

1788670778/representation/deck.py:97:'joinedFields' is deprecated: please use 'joined_fields'
1788670778/representation/deck.py:97:'joinedFields' is deprecated: please use 'joined_fields'
1788670778/representation/deck_initializer.py:10:'byName' is deprecated: please use 'by_name'
1788670778/representation/deck_config.py:12:'getConf' is deprecated: please use 'get_config'

**Comment by aplaice** [comment]
Thanks for bringing this up!

Having such a stream of warning messages in your terminal is probably annoying. Sorry!

Fortunately, from what I'm aware of, this is purely a matter of renaming, not of a changed interface.

To the extent that we don't want to lose compatibility with older versions of Anki (people have various good reasons to stick with older versions of Anki and it'd be nice to at least make bug-fixes available to these people), this might be slightly tricky to get right. (If we don't care about that, it should be just a matter of batch renaming.)
