### ISSUE TITLE
Deck name vs. repository name

### ISSUE THREAD

**Issue by axelboc** [Stvad/CrowdAnki#15]
- On export, CrowdAnki outputs a folder named after the deck - e.g. _My Deck_ becomes `My_Deck`.
- To import from GitHub, CrowdAnki requires the repository to be named after the deck - e.g. `My_Deck`.

I'm not very keen on having the name of my GitHub repo bound to the name of the deck. I think the add-on would really benefit from a bit more flexibility in this regard.

I can think of a couple of options:

1. Include the name of the deck in the JSON and allow exporting the deck to any folder (i.e. the export doesn't create the folder).
    - **Upside:** nice separation of concern; during the import CrowdAnki can just look for the JSON file and the `media` folder at the root of the repo and parse the content of the file to get the name of the deck.
    - **Downside:** changing the format is not ideal... although for backward compatibility, if the JSON file doesn't contain the name of the deck, its filename could be used as fallback.
2. Keep the export as is, but allow selecting a custom folder inside the git repository during the import.
    - **Upside**: probably more straightforward to implement; no change to the JSON format.
    - **Downside**: superfluous folder nesting; makes import more complex for end users.

**Comment by Stvad** [comment]
Hi, I'm not sure I'm following what is your concern.
The name of the deck is already included in the JSON. And correspondingly code, internally, can handle any correct JSON file (though admittedly there is no UI to do that).
I've chosen to enforce the convention for deck directories to be the representation of the deck name as it was easier to implement and I haven't seen any particular advantage in the 'pick first json file strategy' (though it can be changed without breaking thins).
I've chosen to enforce convention name of the repository==the name of the deck directory for the same reason (and also to reinforce the notion one-repository=one-deck). I can see how the name of the repository may not be the nicest one as a consequence, with hierarchy and platform-specific name limitations.
Do I understand correctly that you would prefer mentioned 'pick first json file strategy' to be in place (that would imply that the repositories can have any valid name as long as they have the correct content in place)?

**Comment by axelboc** [comment]
Ah sorry, I can indeed see the name of the deck in the JSON - not sure how I missed that. It makes my second option irrelevant...

So what I'm suggesting is to remove the first convention you mention that the deck directory has to match the name of the deck.

I think the import can still work the same way: select a folder and look for a JSON file with the same name. What that name is doesn't matter. No need for a 'pick first json file strategy'.

The problem is with the export. A solution might be to have a checkbox that says something like "Create deck directory": 

- If the box is ticked, the behaviour is the same as it is now.
- If the box is unticked, CrowdAnki outputs the JSON file and `media` folder directly at the root of the folder selected by the user, and names the JSON file after that folder.

Does that make sense?

**Comment by Stvad** [comment]
I see, the thing is that right now plugin integrates into export infrastructure already present in Anki (not that it fits well or the infrastructure is any good). And within this constraints, I'm not sure how/where to elegantly fit additional ui options for the export.

**Comment by Stvad** [comment]
#56
