### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfd' in position 18: ordinal not in range(128)

### ISSUE THREAD

**Issue by dominikjenik** [Stvad/CrowdAnki#18]
When exporting collection with texts with special national characters, such as: á é í ó ú č š ž Anki crowd runs into this exception 

> An
> 
>  error occurred in an add-on.
> Please post on the add-on forum:
> https://anki.tenderapp.com/discussions/add-ons
> 
> Traceback (most recent call last):
>   File "aqt\exporting.py", line 116, in accept
>   File "C:\Users\USER\AppData\Roaming\Anki2\addons\crowd_anki\anki_exporter_wrapper.py", line 38, in exportInto
>     self.anki_json_exporter.export_deck_to_directory(deck_name, Path(directory_path).parent, self.includeMedia)
>   File "C:\Users\USER\AppData\Roaming\Anki2\addons\crowd_anki\anki_exporter.py", line 32, in export_deck_to_directory
>     deck_directory = output_dir.joinpath(deck_fsname)
>   File "C:\Users\USER\AppData\Roaming\Anki2\addons\crowd_anki\thirdparty\pathlib2.py", line 1008, in joinpath
>     return self._make_child(args)
>   File "C:\Users\USER\AppData\Roaming\Anki2\addons\crowd_anki\thirdparty\pathlib2.py", line 790, in _make_child
>     drv, root, parts = self._parse_args(args)
>   File "C:\Users\USER\AppData\Roaming\Anki2\addons\crowd_anki\thirdparty\pathlib2.py", line 748, in _parse_args
>     parts.append(str(a))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xfd' in position 18: ordinal not in range(128)

I found it as known issue in python: [discussion 1](https://github.com/pyload/pyload/pull/1951)
[discussion 2](https://stackoverflow.com/questions/31155125/unicodeencodeerror-charmap-codec-cant-encode-character-u-xfd-in-python-2-7)

This is blocker, collection can't be exported at all.

I'm running Anki 2.0.44 and freshly installed plugin.

**Comment by Stvad** [comment]
Can you please attach the collection with which I can reproduce the problem?

**Comment by dominikjenik** [comment]
Thanks to issues with uploading to github and waiting for upload on email....
I have found that it is not matter of cards but matter of name of deck. 
Try create new deck e. g. "fóó" and try to export. It should throw that exception.

**Comment by Stvad** [comment]
It's a problem in the pathlib2. I'm going to update the version packaged with the plugin to fix this problem

**Comment by Stvad** [comment]
Should be fixed in v0.4.4
