### ISSUE TITLE
Automated committing of changes upon AnkiWeb synchronization

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Stvad/CrowdAnki#19]
One thing that would immediately make this useful to me, is if it **automatically** executed `git commit --allow-empty-message -m ''` or similar every time AnkiWeb synchronization completed (and thus, most crucially, *every time I launch or exit Anki*.) I'd really like to only interact with this plugin only to *merge* changes pulled from GitHub or similar … not to export them in the first place, if that makes sense.

Is this do-able? I haven't looked at Anki's plugin-architecture, but I'd hope so …

**Comment by Stvad** [comment]
Will track this in #37
