### ISSUE TITLE
Installing add-on from AnkiWeb does not work

### ISSUE THREAD

**Issue by chrahunt** [Stvad/CrowdAnki#20]
**Expectation:** Installing the add-on from [AnkiWeb](https://ankiweb.net/shared/info/1788670778) like normal would result in the add-on being installed.

**What happened:** After installation there is no indication that the add-on was installed, no item in the Tools > Add-ons menu, and nothing has been added to the File menu or the Export formats dropdown.

**Steps to reproduce:**

1. Using fresh Anki, no add-ons
2. Tools > Add-ons > Browse & install...
3. Paste 1788670778 and Install
4. Restart Anki
5. See no indication that the add-on was installed.

**Anki Version:** 2.0.47 Linux

**Note:** After install my add-ons directory `~/.local/share/Anki2/addons` looked like this:
```
addons/
└─ crowd_anki/
   ├─ crowd_anki_importer.py
   └─ crowd_anki/
      └─ (package files)
```

I moved the files out of the top-level `crowd_anki` directory and restarted Anki, then the plugin worked as expected. For completeness, here is my add-ons directory after the change:

```
addons/
├─ crowd_anki_importer.py
└─ crowd_anki/
   └─ (package files)
```

**Comment by ebauch** [comment]
same bug on Mac OS 10.12.6

**Comment by Stvad** [comment]
Huh, thank you for reporting this.

**Comment by Stvad** [comment]
I've uploaded a fixed version to AnkiWeb and to the latest release.
