### ISSUE TITLE
Convert deck to use CrowdAnki

### ISSUE THREAD

**Issue by Daniel-Groves** [Stvad/CrowdAnki#207]
Is it possible to convert a deck into its CrowdAnki form and save the progress from the deck?

**Comment by aplaice** [comment]
> save the progress from the deck

In the sense of save the review history in the CrowdAnki form (such that if you delete the Anki version of the deck, and import from CrowdAnki your progress is restored)? Unfortunately no.

(It's also not really a design goal — the review history is not something that makes sense to share with other people. There's no theoretical reason why the review history couldn't be exported into the CrowdAnki JSON, but given limited manpower and that it's not really desired for collaboration, it's not something we'd add in the foreseeable future.)

**Comment by Daniel-Groves** [comment]
Understood. I was more thinking if people have started off reviewing with the normal Anki deck and then wish to transfer, but I can see how that isn't a design goal.

**Comment by aplaice** [comment]
> I was more thinking if people have started off reviewing with the normal Anki deck and then wish to transfer

If people start off reviewing the normal Anki deck, and then import the CrowdAnki version, then CrowdAnki correctly recognises the existing notes (using their "GUID") and does not create duplicate notes, just updating them (if there were any updates), but keeping their review history.

i.e. if the deck creator:

1. Creates a deck, exports it as an APKG.
2. Makes some edits to the deck and adds some extra notes.
3. Installs CrowdAnki (or already has it installed) and exports the deck using CrowdAnki.

and a user:

1. First imports the APKG version.
2. Does some reviews.
3. Imports the CrowdAnki version.

then the user correctly ends up with only one copy of the notes from step **1** (but with the deck creator's edits from **2**), with their review history intact and with one copy of the deck creator's extra notes from **2**.

(This also works in reverse — if the user makes changes to their deck, exports to CrowdAnki, sends to the original deck creator and the original deck creator imports that — the deck creator also doesn't lose any of their own review history.)

(It's just that nobody's review history is stored in the CrowdAnki version of the deck (but it is stored in their respective Anki databases), so you can't use the CrowdAnki version as a back up of your reviews or to transfer to another Anki profile etc.)
