### ISSUE TITLE
add support for 24.06.2+

### ISSUE THREAD

**Issue by JustusPan** [Stvad/CrowdAnki#210]
this plugin seems not work with the lastest Anki desktop client(24.06.2).
could you please help to upgrade this plugin?

**Comment by vinniec2** [comment]
right now I have the same version (I downloaded the linux qt6 version from the site) and I was able to install the plugin and export a deck and it works.
I haven't done any other tests.

**Comment by JustusPan** [comment]
@vinniec2 thanks for the information. I have tested it again and this time everything works well.
