### ISSUE TITLE
Importing from disk doesnt remove old cards

### ISSUE THREAD

**Issue by Musicpac** [Stvad/CrowdAnki#216]
I have a big collection of cards, which I try to synchronize with CrowdAnki. The current problem is that a new person is joining the workflow and his version of my deck is pretty old. He has close to 7000 cards that are no longer part of the deck. 
Is there any solution that those cards get deleted when he imports the deck from disk ?

Thanks in advance

**Comment by wyohm** [comment]
This is a known issue. For now, the best work-around is probably by using tags. I haven't had to do this, so I'm not sure of the exact workflow. I think it will depend on what the behavior is for merging updated notes. But it would be something like:
- Add a tag (e.g. "v2024-11-08") to your deck.
- Merge the new person's changes
- Delete notes without your version tag
Make sure to backup first and test to make sure it's doing what you expect.

**Comment by Musicpac** [comment]
Thank you, that is a great workaround.
To add to that: use -tag: to search for cards that dont have the tag
