### ISSUE TITLE
Make ‘respecting the movement of cards between decks’ optional

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Stvad/CrowdAnki#23]
The documentation states that, if a card is in a different deck when a CrowdAnki deck is imported, that it will be moved in Anki as well.

This should be optional: decks should be able to be, optionally, ’virtual‘ — that is, a “Foo” deck with 24 cards is imported, but then those cards are *moved* by the user into another “Major” deck with hundreds of other cards, then re-importing “Foo” should simply update those notes/cards where they already exist: in the “Major” deck.

The issue here is scalability: Anki (as mentioned in the manual) doesn't handle large numbers of decks, well. It's pretty standard practice to distribute a *subset* of information in a “shared deck”, but usually, one *merges* many of those into a single deck *per subject* (or writes their own cards about that subject, that don't belong in the original shared deck, or … you get the idea.) Thus, it makes sense for (most) CrowdAnki decks to be ‘virtual’ like that: import them, merge them into your *own* subject-specific decks, and then merge upstream changes as they're offered.

(Really the only situation where one wants ‘concrete’ decks, ones that precisely match the CrowdAnki representation, and follow said representation when it's imported if it's changed, is when one is using CrowdAnki to backup/record one's entire collection — and that's currently not well-supported in other ways, so …)

Just some thoughts! `(=`

**Comment by Stvad** [comment]
Maybe I'm missing something, but why do you need to merge the decks if you can have a hierarchy of them?

**Comment by ELLIOTTCABLE** [comment]
@Stvad cf. <https://apps.ankiweb.net/docs/manual.html#using-decks-appropriately>

**Comment by ohare93** [comment]
People do not use CrowdAnki to merge _decks_ but to merge _notes_. Using this type of system allows us to manage and maintain the **content** of the notes, owever which deck each user decides to put those notes

**Comment by Stvad** [comment]
Also discussed more in #8 with a fork there proposing a prototype for basic way to make this configurable (https://github.com/dayjaby/CrowdAnki/commit/39c9666d58b16483631c13521597ae38a9d66cfa)

**Comment by ohare93** [comment]
I have submitted PR (#69) which fixes this issue 👍 @ELLIOTTCABLE

**Comment by ohare93** [comment]
(pinging @dayjaby too, as he complained about this in Issue #8)

**Comment by ohare93** [comment]
Issue is now fixed 👍 there is now an option in the config settings to not move notes on import (see PR #69)
