### ISSUE TITLE
Anki 2.1

### ISSUE THREAD

**Issue by dufferzafar** [Stvad/CrowdAnki#32]
Couldn't install it on Anki 2.1 (from AnkiWeb)

Is the plugin compatible? Are there any plans for future?

**Comment by Stvad** [comment]
Yes, it is compatible. could you be more specific regarding your problem?

**Comment by dufferzafar** [comment]
I'm running Anki v2.1.2

Went to: https://ankiweb.net/shared/info/1788670778

Copied the code `1788670778` into the Get Addons dialog and Anki couldn't install it.

**Comment by Stvad** [comment]
when you say "Anki could not install it" what do you mean? 
Did it give you any error? Did it crash? Did it just ignore your attempts to install the plugin? Did it get installed but does not provide expected functionality?

**Comment by dufferzafar** [comment]
Hey, I'm sorry for this.

I closed Anki and started it again, and this time it got installed.

Previously it was throwing an error like: "Invalid code, or add-on not available for your version of Anki."
