### ISSUE TITLE
Import deck from git repository link

### ISSUE THREAD

**Issue by evolverine** [Stvad/CrowdAnki#46]
Instead of just downloading the repository, collaboration on decks requires cloning repositories, in order to have the original remote configured, so that people can push their changes to github.

**Comment by Stvad** [comment]
The original design was caused by the fact that there was no actual git integration present. Now with dulwich being one of the dependencies this should be fairly easy to implement.

**Some requirements:**

* Clone into the snapshot directory
* If repository already exists in snapshot directory
    * Do `git remote add` (if not present)
    * `git pull <new remote> master`

**Comment by evolverine** [comment]
working on this now, should have a pull request ready in a couple of days.

**Comment by Stvad** [comment]
nice! Thank you!
