### ISSUE TITLE
How to add snapshot path

### ISSUE THREAD

**Issue by qriousguy** [Stvad/CrowdAnki#55]
Hi,
Sorry for this noob question regarding snapshots in crowdanki. I want to use the snapshot feature of crowdanki to keep track of my deck edits. So, based on the guide I made an account on github and installed the desktop client. I tried to input the default github directory into the configuration file for the addon. However, I got the following error. Kindly help.

> Invalid configuration: JSONDecodeError('InvaIid line 2 column 22 (char 23)',)

```
{
	"snapshot_path": "C:\Users\.....\Documents\GitHub"
    "automated_snapshot": false,
    "snapshot_root_decks": []
}
```

**Comment by Stvad** [comment]
Hey!  
I think it's caused by the fac that there is no missing coma after first line.

**Comment by Stvad** [comment]
Btw, you don't actually need the GitHub account to maintain the edit history, though it can be a good idea if you want to maintain a backup of it not on your computer or collaborate with other people on deck creation :)

**Comment by qriousguy** [comment]
Adding comma doesn't help, still same error.
How can I do it without GitHub?

**Comment by Stvad** [comment]
You still need the coma, but it appers that another problem here is backslashes - apparently you have to escape them in JSON, so the valid JSON would look like:
```
{
	"snapshot_path": "C:\\Users\\Arnav Kalra\\Documents\\GitHub",
	"automated_snapshot": false,
	"snapshot_root_decks": []
}
```

For future reference - you can use tools like https://jsonformatter.curiousconcept.com/ to validate your JSON

**Comment by Stvad** [comment]
To have history without GitHub - you don't have to do anything in addition to just taking CrowdAnki snaphots to any place. You'll still need to have a git client to view history though

**Comment by qriousguy** [comment]
> 
> 
> You still need the coma, but it appers that another problem here is backslashes - apparently you have to escape them in JSON, so the valid JSON would look like:
> 
> ```
> {
> 	"snapshot_path": "C:\\Users\\Arnav Kalra\\Documents\\GitHub",
> 	"automated_snapshot": false,
> 	"snapshot_root_decks": []
> }
> ```
> 
> For future reference - you can use tools like https://jsonformatter.curiousconcept.com/ to validate your JSON

It worked, Thanks :)
