### ISSUE TITLE
NoModuleFoundError while loading CrowadAnki addon

### ISSUE THREAD

**Issue by rjraya** [Stvad/CrowdAnki#58]
After adding the complement on Anki, I get the following error that says that the complement failed to load:

![image](https://user-images.githubusercontent.com/11066157/56861765-716c8080-69a4-11e9-9e33-488db542ece0.png)

I'm on Windows 10, Anki version 2.1.5

**Comment by Stvad** [comment]
This is a weird one 🤔 The pathlib is part of stdlib, and AFAIK not the part that is removed in the Anki packaging process

**Comment by Stvad** [comment]
Can you please trying to update Anki to the latest version and seeing if issue persists?

**Comment by rjraya** [comment]
I updated and the problem seems to be solved. Thank you
