### ISSUE TITLE
Unable to export deck as .json

### ISSUE THREAD

**Issue by Vezqi** [Stvad/CrowdAnki#59]
I'm currently running Anki 2.0 on Win 10, and running into this exception when trying to export a single deck as JSON.

Edit: Removing the `/` from the deck name fixed this issue.

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\exporting.py", line 116, in accept
  File "C:\Users\User\AppData\Roaming\Anki2\addons\crowd_anki\anki_exporter_wrapper.py", line 37, in exportInto
    self.anki_json_exporter.export_deck_to_directory(deck_name, Path(directory_path).parent, self.includeMedia)
  File "C:\Users\User\AppData\Roaming\Anki2\addons\crowd_anki\anki_exporter.py", line 40, in export_deck_to_directory
    with deck_filename.open(mode='w', encoding="utf8") as deck_file:
  File "C:\Users\User\AppData\Roaming\Anki2\addons\crowd_anki\thirdparty\pathlib2.py", line 1385, in open
    encoding, errors, newline)
IOError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Desktop\\Core_2k\\6k_Optimized_Japanese_Vocabulary\\Core_2k\\6k_Optimized_Japanese_Vocabulary.json'
```

**Comment by Stvad** [comment]
Hey the plugin is not actively supported fort the Anki 2.0. 

That said it did work for it before (I imagine you got an old version from the addon website), and the 'C:\\Users\\User\\Desktop\\Core_2k\\6k_Optimized_Japanese_Vocabulary\\Core_2k\\6k_Optimized_Japanese_Vocabulary.json' path looks rather suspect. Does it happen on attempt to export any deck?

**Comment by Vezqi** [comment]
It works with other decks just fine, just as long as there isn't a `/` in the deck name. Other than that, every deck seems to export fine with no issues.

**Comment by Stvad** [comment]
I believe this one is fixed in the latest version (works only with Anki 2.1)
