### ISSUE TITLE
UUIDs differ

### ISSUE THREAD

**Issue by johnlawrenceaspden** [Stvad/CrowdAnki#60]
I've got anki running on two computers (and also two mobile phones) , all synced through ankiweb. 

If I export my deck on my laptop, all is fine, but if I export it on the desktop computer I get a completely different set of uuids in the .json, which of course git thinks is a vast set of changes.

This seems to be a problem, what should I do? I can see that I could only use one computer for exporting/uploading changes, but won't any potential collaborators have the same issues?

**Comment by Stvad** [comment]
Hey, I think the problem is that AnkiWeb does not sync the CrowdAnki UUIDs. If you are to do CrowdAnki export on one computer and then import the result on the other one, then on subsequent export from the other computer  the UUID would be preserved.

**Comment by johnlawrenceaspden** [comment]
Thanks, I think you're right, importing the json deck on the other computer seems to cause no damage and stabilises all the UUIDs, presumably replacing all existing UUIDs in the deck, so no problem once one understands the problem, but it's a bit scary the first time you run into it. 

Perhaps you could generate the UUIDs deterministically by hashing the deck name, card number, and so on in a way that would be computer independent and not require syncing them?

Anyway, absolutely loving CrowdAnki so far, good work!

**Comment by Stvad** [comment]
>Perhaps you could generate the UUIDs deterministically by hashing the deck name, card number, and so on in a way that would be computer independent and not require syncing them?

The problem with this scheme is that people tend to rename/move their decks
