### ISSUE TITLE
Import deck from disk

### ISSUE THREAD

**Issue by aleaco** [Stvad/CrowdAnki#63]
Traceback (most recent call last):
  File "E:\ki\mydata\addons\crowd_anki\main.py", line 18, in on_import_action
    directory_path = str(QFileDialog.getExistingDirectory(caption="Select Deck Directory"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)

**Comment by Stvad** [comment]
Hi, can you please provide more information? Things like:

* OS
* Version of Anki
* Full path to the deck
* Name of the deck

Would be useful
