### ISSUE TITLE
What should happend with deleted note from JSON ?

### ISSUE THREAD

**Issue by xmaillard** [Stvad/CrowdAnki#64]
Hello,

I am using anki-dm with CrowdAnki. I thought it was the best way to go but, I see there are merge problems.

If I am deleting a note or modifying a tag on a note and sync back to Anki (anki-dm index, build and then import from disk), I see ods. Either the deleted note is still there (hum ?) or there is no update on the tags.

What am I missing here ?

Thanks

**Comment by Stvad** [comment]
Hey! Sorry, I totally missed this. I trust you've figured things out?
