### ISSUE TITLE
Allow the possibility of not creating a separate folder on export

### ISSUE THREAD

**Issue by evolverine** [Stvad/CrowdAnki#76]
Instead, just use the one the user selects.

User story: My deck name included its parent (because it was not a top-level deck), and the exported folder became something like "Active__deckName". Now, I don't want the folder that houses the deck.json to have this name, firstly because it's unwieldy. Secondly, if I make the deck within Anki a child of a different deck (or if I move it to the top level), it would mean the folder name also changes. But the folder I host these files in should have nothing to do with my Anki deck structure; it should always stay the same. So until now I had a bash script which I used after exporting that basically copied `deck.json` and the media folder into the parent folder, then deleted the generated "Active__deckName" folder. But, really, there's no need for this extra nuisance: the export contents can simply be placed directly in the folder the user selects.

**Comment by Stvad** [comment]
Use case for having a hosting directory is exporting multiple decks into the same holding directory.   
You rise valid questions, but I think given the use case above and that this is how it's been for a while now (i.e. people have incorporated it in their workflows) just stopping doing it is not a solution.  
At the very least this should be configurable in the settings + snapshotting code needs to be updated

**Comment by evolverine** [comment]
What about a checkbox on the export dialogue?

**Comment by Stvad** [comment]
That'd work too, but CrowdAnki uses Anki's export dialog so not much room for customization there probably
