### ISSUE TITLE
Add GitHub Topic: anki-flashcards

### ISSUE THREAD

**Issue by katrinleinweber** [Stvad/CrowdAnki#79]
Thanks for publishing this! In case you'd like to make [your repo more findable](https://github.com/topics/anki-flashcards), you could [add that topic](https://help.github.com/articles/about-topics/), or another common topic that those other projects already use ;-) Thank you!

**Comment by Stvad** [comment]
done, thank you!

**Comment by katrinleinweber** [comment]
Merci :-)
