### ISSUE TITLE
Don't block Anki GUI with "snapshot ... successfully completed" dialogue

### ISSUE THREAD

**Issue by katrinleinweber** [Stvad/CrowdAnki#80]
This is a request to revert 915994d6f235b63b517c5788fc69f66a1e95e63a. If everything went well, I'd like to continue working without interruption. That is IMHO acceptable in case of problems I need to take care of. cc @evolverine ;-)

Maybe it can be turned into a non-interaction-requiring notification?

**Comment by Stvad** [comment]
I believe feedback on the success is important. It can be done via a different style of notification though yes

**Comment by katrinleinweber** [comment]
Thank you :-)
