### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by aPaci95** [Stvad/CrowdAnki#83]
Hello Stvad, i'm sorry if i'm submitting an issue but i didn't find any way to contact you outside github. Me and a bunch of anki developers like arthur milchior are discussing the idea of creating an  addon that allow wikipedia-like collaborative decks; something like your addon but much more user-friendly (wikipedia-like), where you can access the shared deck, pull cards made by you to improve the deck, or pull fixes, or even fork the notes that you want to edit for your purpose.
If you are interested to see this happen, or even want to contribute to its development, please join the official anki discord where we'are talking about this https://discord.gg/mwuDKwG

**Comment by ohare93** [comment]
Joined :wink:

**Comment by Stvad** [comment]
Hey @aPaci95 I'd be happy to chat about it :) , but I don't think I would be able to dedicate much development time to it at this moment
