### ISSUE TITLE
Compatibility issues with the new version of Anki

### ISSUE THREAD

**Issue by RT94** [Stvad/CrowdAnki#84]
Hey @Stvad ! I love and appreciate the work you put into this addon. I am having an issue with importing decks from any source (disk or github). Please let me know what I can do to fix this. Here is the error:
![image](https://user-images.githubusercontent.com/64577185/81512912-7cb1f600-92f2-11ea-9053-aa61a9e9902a.png)

Here are my addons:
![image](https://user-images.githubusercontent.com/64577185/81512972-d3b7cb00-92f2-11ea-814d-af1d8fd4daee.png)

**Comment by xiaoxiae** [comment]
Having the same issue, with the only addon installed being CrowdAnki.

**Comment by RT94** [comment]
Thanks for checking that. I guess I will have to wait for an update to this because I have a lot of add-ons so it may cause a problem when downgrading since there's been a lot of changes to Anki since that version.

**Comment by Stvad** [comment]
Yeah, it does seem like an update to Anki internals breaking CrowdAnki =\. I'll try to investigate next week

**Comment by RT94** [comment]
Sounds good man. Thanks for looking into it

**Comment by josealberto4444** [comment]
Same error for me with only this addon installed. I'll paste the debug info so you can see another, in case it helps having another from other system:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (arch-linux-2.1.26-1) Python 3.8.3 Qt 5.14.2 PyQt 5.14.2
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2020-05-23 15:29:47
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩

Caught exception:
Traceback (most recent call last):
  File "/home/jose/.local/share/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/home/jose/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 91, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/home/jose/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 80, in import_deck_from_path
    importer.load_from_directory(directory_path, import_media)
  File "/home/jose/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 46, in load_from_directory
    self.load_from_file(self.get_deck_path(directory_path))
  File "/home/jose/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 31, in load_from_file
    deck.save_to_collection(self.collection)
  File "/home/jose/.local/share/Anki2/addons21/1788670778/representation/deck.py", line 135, in save_to_collection
    config.save_to_collection(collection)
  File "/home/jose/.local/share/Anki2/addons21/1788670778/representation/deck_config.py", line 20, in save_to_collection
    config_dict = collection.decks.get_deck_config_by_uuid(self.get_uuid())
  File "/home/jose/.local/share/Anki2/addons21/1788670778/anki/overrides/uuid_operations.py", line 37, in get_deck_configuration_by_uuid
    return get_from_dict_by_uuid(self, "dconf", uuid)
  File "/home/jose/.local/share/Anki2/addons21/1788670778/anki/overrides/uuid_operations.py", line 23, in get_from_dict_by_uuid
    for value in (getattr(base_object, dict_name)).values():
AttributeError: 'DeckManager' object has no attribute 'dconf'
```

Thanks in advance.

**Comment by ohare93** [comment]
I have a working hotfix for this issue in the PR #85 :+1: though it may take some more fleshing out to get a proper fix pulled in, as there's some intricacy to the changes done recently in Anki. If you are impatient and want CrowdAnki to work with latest Anki feel free to pull this change (or just change the 3 lines as I have done), re-export the deck (which will add the missing values Anki now wants), then you can import successfully :+1:

**Comment by Stvad** [comment]
Anki codebase has undergone very extensive changes =\. I'll try to do some updates, but I feel like a really deep dive/testing needed here to ensure that CrowdAnki still properly interacts with the main codebase in other aspects

**Comment by Stvad** [comment]
Ok, I have preliminary fix in #86 would appreciate people testing it out

**Comment by RT94** [comment]
I would love to help in testing this, but since I am new to github, I do not know how to help. If one of you all could please guide me around, that would be great

**Comment by Stvad** [comment]
https://github.com/Stvad/CrowdAnki/blob/master/CONTRIBUTING.md#testing has instructions, but they require some technical background

**Comment by RT94** [comment]
I tried looking into it, however the method of getting the updated addon is pretty far out of my depth. I apologize if this is too much to ask, but is there any way you could upload a compiled ".ankiaddon" build that I can directly install into Anki to test?

**Comment by ohare93** [comment]
Tested the fix and it works on my end :+1:

**Comment by ohare93** [comment]
> I tried looking into it, however the method of getting the updated addon is pretty far out of my depth. I apologize if this is too much to ask, but is there any way you could upload a compiled ".ankiaddon" build that I can directly install into Anki to test?

Not a feasible solution in the long run. 

Download [Github Desktop](https://desktop.github.com/) and follow [these steps](https://help.github.com/en/desktop/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop) to clone this repo. You'll then need to follow the steps in the [Contributing Testing section](https://github.com/Stvad/CrowdAnki/blob/master/CONTRIBUTING.md#testing) to have your repo working, and Anki being able to read it. Here's some [help on Symlinks](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) when you get to that step. 

Good luck! :sweat_smile:

**Comment by RT94** [comment]
I appreciate the guide @ohare93 . I have done all of the steps and Anki is able to detect the addon, however it is not able to load it. I get this error:
![image](https://user-images.githubusercontent.com/64577185/82786331-66e41b00-9e32-11ea-99e1-5f70c6ec025a.png)

Do you know what may be causing this?

**Comment by ohare93** [comment]
@RT94 did you run fetch_dependencies?

**Comment by RT94** [comment]
Yes I did, however the command prompt window only popped up for a second, then disappeared. I checked the crowd_anki directory, however there is no "dist" folder

**Comment by Premik** [comment]
I tried to apply the commit as patch directly to my installed plugin like this (Anki `Version 2.1.26`):

```shell
cd ~/.local/share/Anki2/addons21/1788670778
wget https://github.com/Stvad/CrowdAnki/commit/b10ac2d89e7b830309adfaf399061d76d90fcbe5.patch
patch -p2  <b10ac2d89e7b830309adfaf399061d76d90fcbe5.patch
```

And I think at first I managed to do one successful `export`/ `Import from Disk` cycle.
But now I always get the following exception when I try to import. Even on a freshly created profile, a new basic card. 



```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (arch-linux-2.1.26-1) Python 3.8.3 Qt 5.14.2 PyQt 5.14.2
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2020-05-24 23:27:05
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩

Caught exception:
Traceback (most recent call last):
  File "/home/premik/.local/share/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/home/premik/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 91, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/home/premik/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 80, in import_deck_from_path
    importer.load_from_directory(directory_path, import_media)
  File "/home/premik/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 46, in load_from_directory
    self.load_from_file(self.get_deck_path(directory_path))
  File "/home/premik/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 31, in load_from_file
    deck.save_to_collection(self.collection)
  File "/home/premik/.local/share/Anki2/addons21/1788670778/representation/deck.py", line 136, in save_to_collection
    config.save_to_collection(collection)
  File "/home/premik/.local/share/Anki2/addons21/1788670778/representation/deck_config.py", line 28, in save_to_collection
    config_dict = collection.decks.add_config(self.anki_dict["name"], self.anki_dict)
  File "/usr/lib/python3.8/site-packages/anki/decks.py", line 368, in add_config
    self.update_config(conf)
  File "/usr/lib/python3.8/site-packages/anki/decks.py", line 357, in update_config
    self.col.backend.add_or_update_deck_config(conf, preserve_usn)
  File "/usr/lib/python3.8/site-packages/anki/rsbackend.py", line 519, in add_or_update_deck_config
    id = self._run_command(
  File "/usr/lib/python3.8/site-packages/anki/rsbackend.py", line 257, in _run_command
    raise proto_exception_to_native(output.error)
anki.rsbackend.StringError: JSONError { info: "missing field `mod` at line 1 column 458" }
```
[Export-Default.zip](https://github.com/Stvad/CrowdAnki/files/4676317/Export-Default.zip)
[Profile.zip](https://github.com/Stvad/CrowdAnki/files/4676318/Profile.zip)

**Comment by ohare93** [comment]
@Premik Hmm, that is the error I was getting after my hotfix. I did not experience it again after @Stvad's fix. I will test again when I am home, in 6 hours or so.

**Comment by Stvad** [comment]
Another issue related to the Anki update - snapshot gets stuck on completion

**Comment by Stvad** [comment]
@RT94   what OS are you on?  
@Premik interesting, was able to reproduce with the deck you've attached but not with my own export. Wonder what is different with them..

**Comment by RT94** [comment]
> @RT94   what OS are you on?  

@Stvad I'm using Windows 10 64-bit

**Comment by Stvad** [comment]
@RT94 not sure how well shell scripts work on it these days 🤔 btw did you install pipenv as described in https://github.com/Stvad/CrowdAnki/blob/master/CONTRIBUTING.md#dependencies ?

**Comment by Stvad** [comment]
@Premik I think the issue there was when a new deck config was created (vs updating existing one). I pushed a new update - can you check if that works for you? 
cc @ohare93

**Comment by Stvad** [comment]
Also pushed update for snapshot leading to Anki getting stuck

**Comment by RT94** [comment]
> @RT94 not sure how well shell scripts work on it these days 🤔 btw did you install pipenv as described in https://github.com/Stvad/CrowdAnki/blob/master/CONTRIBUTING.md#dependencies ?

@Stvad I'm unclear on the instructions since the link on the page you directed me says the website is down. Is there a certain command I need to use in the main repo folder?

**Comment by Stvad** [comment]
ugh, it is down. https://pipenv.pypa.io/en/latest/install/#installing-pipenv is another guide

**Comment by Premik** [comment]
> think the issue there was when a new deck config was created (vs updating existing one). I pushed a new update - can you check if that works for you?

I applied the `1be3cf5` on top and I can confirm it fixed the error and I successfully imported the deck. Well done :+1: 

Now regarding the snapshot hanging, I also observed similar one while re-importing an older I exported(ish) earlier. Is it this the same issue or something new? I my case the `Processing` popup never goes away and I have to kill the anki process:

![ImportHang](https://user-images.githubusercontent.com/842962/82845116-7ec7a780-9ee3-11ea-8064-2fc4687abe7d.png)

**Comment by Stvad** [comment]
hmm it does sound similar =\. would it be possible for you to share that decks (current version and the version you're importing)?

**Comment by RT94** [comment]
> ugh, it is down. https://pipenv.pypa.io/en/latest/install/#installing-pipenv is another guide
> 
> eh, it's not that straightforward without a background in these things..

I found a guide that mentioned that I needed to create a command prompt path to pip in the python folder in C:\Users\~\AppData\Local\Programs\Python\Python38-32\Scripts, then I ran the command "pip install pipenv" and it ended up downloading the pipenv files. Is there anything else I need to do?

**Comment by Stvad** [comment]
can you try running `fetch_dependencies` now? or the command from within it directly..

**Comment by RT94** [comment]
@Stvad I just tried that but I'm getting the same problem. The command prompt window opens for just a second and then closes and there's no "dist" directory. My crowdanki folder is located in the documents folder under "Users" on my C: drive. Does this need to be in a different directory?

**Comment by ohare93** [comment]
@Stvad 

> @Premik I think the issue there was when a new deck config was created (vs updating existing one). I pushed a new update - can you check if that works for you?
> cc @ohare93

Works fine now :+1: tried a fully empty profile, as well as an existing one, with a few different decks.

> Also pushed update for snapshot leading to Anki getting stuck

This works too :+1:

**Comment by Premik** [comment]
Reg. the hanging import. This is not related to a specific deck. Seems to  happen each time there is the "Change Note type" migration dialog shown as part of the import process.

1. Import the `Export-Default.zip` above if you haven't import it yet
1. Edit the `deck.json`. Change for instance the fields order in the note model. Any change which triggers the note type migaration would do. Or just take this one: [Export-Default2.zip](https://github.com/Stvad/CrowdAnki/files/4680533/Export-Default2.zip)
1. `Import from disk` the modified json (Export-Default2.zip)

Should see the hang.

Now I recall in the previous anki version there was also something weird about this dialog too. I think the mouse cursor was the `waiting/clock` one all the time. But at least I was still able to click the ok button. But now there seems to be this modal processing dialog on top.

**Comment by Stvad** [comment]
Thanks for elaboration @Premik, I found a culprit - another change in Anki, that now ignores directive to immediately show the progress window. Instead it gets shown later and it's modal, preventing you from interacting with the window that appeared in the meantime =\

**Comment by Stvad** [comment]
Added a fix for that too. Let me know if that works for you

**Comment by Premik** [comment]
Works a treat :+1:  Thanks
