### ISSUE TITLE
Exporting "Species Taxonomy" deck works but it shows 0 cards exported

### ISSUE THREAD

**Issue by ChristianKleineidam** [Stvad/CrowdAnki#9]
I successfully exported the "Species Taxonomy" deck but Anki reports that 0 cards got exported.

**Comment by Stvad** [comment]
Well, that's because 0 cards were exported :smile:. The thing is Anki expects a number here, but I don't export cards, so I'm not sure what should I show here. I agree that leaving 0 is a bit confusing, though. I will look into ways to make it better.

**Comment by ChristianKleineidam** [comment]
Then how about a similar message stating how many notes were exported?
